### ISSUE TITLE
Silence errors from loading external scripts/sheets while disabled

### ISSUE THREAD

**Issue by asportnoy** [capricorn86/happy-dom#1134]
**Is your feature request related to a problem? Please describe.**
I am parsing some HTML with JS and CSS fetching enabled. This document has some external scripts and links which are throwing unhandledRejection errors due to the fetching being disabled. (We have a listener set up to log these instead of exiting)
```
NotSupportedError: Failed to load external stylesheet "https://example.com/style.css". CSS file loading is disabled.
    at Function.loadExternalStylesheet (file:///{REDACTED}/node_modules/happy-dom/lib/nodes/html-link-element/HTMLLinkElementUtility.js:23:31)
    at HTMLLinkElement._connectToNode (file:///{REDACTED}/node_modules/happy-dom/lib/nodes/html-link-element/HTMLLinkElement.js:168:36)
    at HTMLElement._connectToNode (file:///{REDACTED}/node_modules/happy-dom/lib/nodes/node/Node.js:348:23)
    at HTMLElement._connectToNode (file:///{REDACTED}/node_modules/happy-dom/lib/nodes/node/Node.js:348:23)
    at Function.appendChild (file:///{REDACTED}/node_modules/happy-dom/lib/nodes/node/NodeUtility.js:46:14)
    at Function.appendChild (file:///{REDACTED}/node_modules/happy-dom/lib/nodes/element/ElementUtility.js:48:25)
    at HTMLDocument.appendChild (file:///{REDACTED}/node_modules/happy-dom/lib/nodes/document/Document.js:566:31)
    at HTMLDocument.write (file:///{REDACTED}/node_modules/happy-dom/lib/nodes/document/Document.js:618:26)
    at createDOMFromHTML (file:///{REDACTED}/server/utils/dom.js:55:14)
    at Suite.<anonymous> (file:///{REDACTED}/test/utils/dom.test.js:23:20) {name: 'NotSupportedError', stack: 'NotSupportedError: Failed to load external st…{REDACTED}/test/utils/dom.test.js:23:20)', message: 'Failed to load external stylesheet "https://…om/style.css". CSS file loading is disabled.'}
```

**Describe the solution you'd like**
It would be great if these error logs could be disabled, either by default or through an additional setting. Having more control over errors in general would also be great. Maybe there's a way to do this that's just undocumented? If so please let me know.

**Describe alternatives you've considered**
I added some additional handling to our unhandled rejection handler to silence these logs for now, but it's not ideal for a number of reasons, and would be much better if built in.
```js
export const shouldIgnoreDomError = (error) => {
    if (!(error instanceof DOMException)) return false;
    if (
        error.name === DOMExceptionNameEnum.notSupportedError &&
        /Failed to load external (script|stylesheet)/.test(error.message)
    ) {
        return true;
    }

    return false;
};
```

**Additional context**
happy-dom v12.9.1
NodeJS v16.20.2

**Comment by asportnoy** [comment]
Turns out I accidentally set `disableErrorCapturing` to `true` in my options and that's what was causing the issue. After setting that to false, nothing is logged.
