### ISSUE TITLE
Fails on non-string append values

### ISSUE THREAD

**Issue by martypdx** [capricorn86/happy-dom#1246]
**Describe the bug**

Using an append method  (`append`, `before`, `afer`, etc.) on a DOM Node (element, comment, etc.) with a non string value throws an error. Should coerce value to string and use it.

**To Reproduce**

[Stackblitz repo](https://stackblitz.com/edit/stackblitz-starters-jzbfyn?file=index.js)

```js
import { Window } from 'happy-dom';
const window = new Window({ url: 'https://localhost:8080' });
const document = window.document;
const div = document.createElement('div');
div.append(42); // fails here
console.log(div.outerHTML);
```
 Yields:

```
Error: Cannot read properties of undefined (reading 'length')
    at _0xb418b8._evaluate (https://stackblitzstartersjzbfyn-4b51.w-credentialless.staticblitz.com/blitz.69a3aa37.js:352:377970)
    at async ModuleJob.run (https://stackblitzstartersjzbfyn-4b51.w-credentialless.staticblitz.com/blitz.69a3aa37.js:181:2372)
```

**Expected behavior**

Converts the value to a string and appends to target node

**Screenshots**

Browser behavior:

![image](https://github.com/capricorn86/happy-dom-without-node/assets/478864/219a8b4c-49b1-4210-99df-c7fcdff0a4f1)

**Device:**

Standard library using node

**Additional context**

For me, road block to using `happy-dom` as a vitest environment runner

**Comment by martypdx** [comment]
Temporary workaround that can be applied to the value:

```js
    // happy-dom bug for non-string values
    const type = typeof input;
    const isDomNode = input instanceof Node;
    if(type !== 'string' && !isDomNode) {
        input = `${input}`;
    }

    anchor.before(input);
```

**Comment by karpiuMG** [comment]
@capricorn86 to be closed

https://stackblitz.com/edit/vitejs-vite-ukmtoes2?file=src%2FApp.test.tsx
