### ISSUE TITLE
Calling `new HTMLElement()` throws exception

### ISSUE THREAD

**Issue by gerbyzation** [capricorn86/happy-dom#1481]
**Describe the bug**
`happy-dom@>13.0.5` throws an exception when calling `new HTMLElement()`

**To Reproduce**

```js
// repro.mjs
import { HTMLElement } from "happy-dom";

const el = new HTMLElement();
```
```
$ node repro.mjs
file:///Users/gerbenneven/projects/some-project/node_modules/.pnpm/happy-dom@14.12.3/node_modules/happy-dom/lib/nodes/node/Node.js:34
                throw new Error('Failed to construct "Node": No owner document in queue. Please use "NodeFactory" to create instances of a Node.');
                      ^

Error: Failed to construct "Node": No owner document in queue. Please use "NodeFactory" to create instances of a Node.
    at new Node (file:///Users/gerbenneven/projects/some-project/node_modules/.pnpm/happy-dom@14.12.3/node_modules/happy-dom/lib/nodes/node/Node.js:34:23)
    at new Element (file:///Users/gerbenneven/projects/some-project/node_modules/.pnpm/happy-dom@14.12.3/node_modules/happy-dom/lib/nodes/element/Element.js:28:9)
    at new HTMLElement (file:///Users/gerbenneven/projects/some-project/node_modules/.pnpm/happy-dom@14.12.3/node_modules/happy-dom/lib/nodes/html-element/HTMLElement.js:32:9)
    at file:///Users/gerbenneven/projects/some-project/dom-test.mjs:3:12
    at ModuleJob.run (node:internal/modules/esm/module_job:217:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:308:24)
    at async loadESM (node:internal/process/esm_loader:42:7)
    at async handleMainPromise (node:internal/modules/run_main:66:12)

Node.js v20.6.1
```

**Expected behavior**
No exception to throw. Earlier versions (`happy-dom@<=13.0.5`) supported this without issue

**Device:**
 - OS: macOS Sonoma 14.05 
 - Browser: n/a
 - Version: node 20.6.1

**Additional context**

**Comment by capricorn86** [comment]
Thank you for reporting @gerbyzation! :slightly_smiling_face: 

This is not something that the browser supports either. The problem is that the element needs to be aware of its context (window, document etc.) already while it is constructed.

I'm closing this as the goal is to follow the spec as much as possible, which is to throw an "Illegal constructor" error.
