### ISSUE TITLE
`document.write` fails when writing a document with `<html>` but without a `<body>`

### ISSUE THREAD

**Issue by rijenkii** [capricorn86/happy-dom#1548]
**Describe the bug**
Trying to write `<html></html>` into a document results in a following error:
```
DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
    at [insertBefore] (/tmp/happydomtest/node_modules/happy-dom/cjs/nodes/node/Node.cjs:518:19)
    at [insertBefore] (/tmp/happydomtest/node_modules/happy-dom/cjs/nodes/element/Element.cjs:1016:63)
    at HTMLHtmlElement.insertBefore (/tmp/happydomtest/node_modules/happy-dom/cjs/nodes/node/Node.cjs:353:49)
    at HTMLDocument.write (/tmp/happydomtest/node_modules/happy-dom/cjs/nodes/document/Document.cjs:676:41)
```

**To Reproduce**
1. `npm install happy-dom@15.7.4`
2. `echo 'new (require("happy-dom")).Window().document.write("<html></html>")' | node`
1. See error

**Expected behavior**
Call should have succeeded, as it does in the browsers:
![image](https://github.com/user-attachments/assets/8e830043-188a-4ec8-aabe-133f1b33189a)

**Comment by capricorn86** [comment]
Thank you reporting @rijenkii! :slightly_smiling_face: 

I believe this bug has been fixed in v16.0.0
