### ISSUE TITLE
happy-dom tries to fetch resources if script tag is added to document

### ISSUE THREAD

**Issue by jansepke** [capricorn86/happy-dom#1552]
**Describe the bug**
We want to test a simple asset loader that loads other JS files by inserting script tags into the document. This test worked with JSDom but happy-dom is really trying to fetch the asset. We also tried MSW to mock that request but that also did not work.

**To Reproduce**
Create this simple test case (e.g. with vitest + happy-dom)
```typescript
test('script tag creation', () => {
  const script = document.createElement('script');
  script.src = 'http://localhost/assets/script.js';
  script.async = true;
  document.head.appendChild(script);
});
```

**Expected behavior**
I don't get any errors.

**Actual behavior**
```
Error: connect ECONNREFUSED 127.0.0.1:80
    at __node_internal_captureLargerStackTrace2 (https://vitestdevvitestepnkcu-emh3.w-credentialless-staticblitz.com/builtins.ddb8d84d.js:101:5335)
    at __node_internal_exceptionWithHostPort2 (https://vitestdevvitestepnkcu-emh3.w-credentialless-staticblitz.com/builtins.ddb8d84d.js:101:7017)
    at _0x30e61d.afterConnect [as oncomplete] (https://vitestdevvitestepnkcu-emh3.w-credentialless-staticblitz.com/builtins.ddb8d84d.js:285:9237)
    at https://vitestdevvitestepnkcu-emh3.w-credentialless-staticblitz.com/blitz.e7ca9335.js:40:1004090 {
  errno: -61,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 80
}
Error: Failed to execute "fetch()" on "Window" with URL "http://localhost/assets/script.js": connect ECONNREFUSED 127.0.0.1:80
    at new DOMException (file:///home/projects/vitest-dev-vitest-epnkcu/node_modules/happy-dom/lib/exception/DOMException.js:31:9)
    at new DOMException (file:///home/projects/vitest-dev-vitest-epnkcu/node_modules/happy-dom/src/window/WindowClassExtender.ts:178:20)
    at Fetch.onError (file:///home/projects/vitest-dev-vitest-epnkcu/node_modules/happy-dom/src/fetch/Fetch.ts:518:12)
    at ClientRequest.emit (node:events:30:10899)
    at Socket.socketErrorListener (node:_http_client:3:5615)
    at Socket.emit (node:events:30:10899)
    at emitErrorNT (node:internal/streams/destroy:215:1091)
    at emitErrorCloseNT (node:internal/streams/destroy:215:746)
    at processTicksAndRejections (node:internal/process/task_queues:192:1067)
    at https://vitestdevvitestepnkcu-emh3.w-credentialless-staticblitz.com/blitz.e7ca9335.js:40:198953 {
  name: 'NetworkError'
}
```

**Device:**
 - stackblitz link: https://stackblitz.com/edit/vitest-dev-vitest-epnkcu?file=test%2Fbasic.test.ts&view=editor

**Comment by jansepke** [comment]
I found the solution in the [happy-dom settings](https://github.com/capricorn86/happy-dom/wiki/IOptionalBrowserSettings). adding this to the jest config disables the problematic behaviour:
```json
"testEnvironmentOptions": {
      "settings": {
        "disableJavaScriptFileLoading": true,
        "disableCSSFileLoading": true,
        "handleDisabledFileLoadingAsSuccess": true
      }
    }
```
