### ISSUE TITLE
React issue

### ISSUE THREAD

**Issue by dy** [capricorn86/happy-dom#25]
Running tests for [enhook](https://ghub.io/enhook), getting the following.

```sh
# react
(node:5736) UnhandledPromiseRejectionWarning: TypeError: Right-hand side of 'instanceof' is not an object
    at getActiveElementDeep (C:\projects\enhook\node_modules\react-dom\cjs\react-dom.development.js:8903:18)
    at getSelectionInformation (C:\projects\enhook\node_modules\react-dom\cjs\react-dom.development.js:8934:21)
    at prepareForCommit (C:\projects\enhook\node_modules\react-dom\cjs\react-dom.development.js:9447:26)
    at commitRootImpl (C:\projects\enhook\node_modules\react-dom\cjs\react-dom.development.js:24973:5)
    at unstable_runWithPriority (C:\projects\enhook\node_modules\scheduler\cjs\scheduler.development.js:818:12)
    at runWithPriority$2 (C:\projects\enhook\node_modules\react-dom\cjs\react-dom.development.js:12130:10)
    at commitRoot (C:\projects\enhook\node_modules\react-dom\cjs\react-dom.development.js:24889:3)
    at finishSyncRender (C:\projects\enhook\node_modules\react-dom\cjs\react-dom.development.js:24296:3)
    at performSyncWorkOnRoot (C:\projects\enhook\node_modules\react-dom\cjs\react-dom.development.js:24274:9)
    at scheduleUpdateOnFiber (C:\projects\enhook\node_modules\react-dom\cjs\react-dom.development.js:23665:7)
(node:5736) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
```

Not sure what's the reason, due to incredibly obscure nature of react I can't even figure out where the error is coming from.
I'll just leave it here in hope somebody else will stumble upon it too, with less vague context.

**Comment by capricorn86** [comment]
Hi @dy!

Sorry for a late reply. I have been quite busy lately with some personal matter.

I am working on v1.0.0 which will have some minor API changes, but mostly it is about creating a lot of unit tests and integration tests. I will make sure to put in tests for React as well. I will let you know when I have got them to work.

**Comment by capricorn86** [comment]
Hi @dy!

Sorry that it has taken such a long time before I could release v1.0.0.

Happy DOM now has support for React together with a bunch of other features.

I will now close this issue.
