### ISSUE TITLE
TypeError: l.getAttributeNames is not a function or its return value is not iterable

### ISSUE THREAD

**Issue by Dolfeeuw** [capricorn86/happy-dom#291]
After a lot of trying and testing, I have stumbled onto this package, and some tests finally seem to work at least, so first of all, thanks for that :-).

However when I add a property as a class to my Lit custom element and test it using the happy-dom test environment I get the following error stacktrace:

**TypeError: l.getAttributeNames is not a function or its return value is not iterable**

      at new V (node_modules/lit/node_modules/lit-html/src/lit-html.ts:702:48)
      at S._$getTemplate [as _$AC] (node_modules/lit/node_modules/lit-html/src/lit-html.ts:1257:53)
      at S._commitTemplateResult [as T] (node_modules/lit/node_modules/lit-html/src/lit-html.ts:1236:16)
      at S._$setValue [as _$AI] (node_modules/lit/node_modules/lit-html/src/lit-html.ts:1140:12)
      at render (node_modules/lit/node_modules/lit-html/src/lit-html.ts:429:8)
      at HTMLSelectElement.update (node_modules/lit/node_modules/lit-element/src/lit-element.ts:136:24)
      at HTMLSelectElement.performUpdate (node_modules/@lit/reactive-element/src/reactive-element.ts:1125:14)
      at HTMLSelectElement.scheduleUpdate (node_modules/@lit/reactive-element/src/reactive-element.ts:1058:17)
      at HTMLSelectElement._$EC (node_modules/@lit/reactive-element/src/reactive-element.ts:1030:25)`

this is my migrated component (from lit-element to lit)
https://github.com/michellecap/lit/blob/6062c88590e17dfec5bc9ff597f42f66ae258ae6/src/testComponent.js#L1-L30

And this is my testfile:
https://github.com/michellecap/lit/blob/ce600c4eb4818691e8a504ad41e0f771b92ffc4e/src/testComponent.spec.js#L1-L31

Wondering if something is wrong with the setup, the migration to lit, or with the package?

**Comment by capricorn86** [comment]
Thanks for reporting @Dolfeeuw! :slightly_smiling_face: 

It seems like HappyDOM was missing support for Element.getAttributeNames(), which has now been added. Can you please test with the latest release and see if it solves your problem? I can try to replicate your environment if it does not work.

Read more about the release:
https://github.com/capricorn86/happy-dom/releases/tag/v2.23.0
