### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'HTMLIFrameElement') with React and Testing Library

### ISSUE THREAD

**Issue by lencioni** [capricorn86/happy-dom#460]
I'm looking to try out happy-dom as a replacement for jsdom in my tests and I've run into a speed bump. Here's my test:

```tsx
/**
 * @jest-environment @happy-dom/jest-environment
 */

import React from 'react';
import { render } from '@testing-library/react';

function Foo() {
  return <div>Foo</div>;
}

it('works', () => {
  render(<Foo />);
});
```

Unfortunately, this results in an error with this stack trace:

```
    TypeError: Cannot read properties of undefined (reading 'HTMLIFrameElement')

      at getActiveElementDeep (node_modules/react-dom/cjs/react-dom.development.js:6941:33)
      at getSelectionInformation (node_modules/react-dom/cjs/react-dom.development.js:6972:21)
      at prepareForCommit (node_modules/react-dom/cjs/react-dom.development.js:7463:26)
      at commitRootImpl (node_modules/react-dom/cjs/react-dom.development.js:22474:5)
      at unstable_runWithPriority (node_modules/scheduler/cjs/scheduler.development.js:653:12)
      at runWithPriority$1 (node_modules/react-dom/cjs/react-dom.development.js:11039:10)
      at commitRoot (node_modules/react-dom/cjs/react-dom.development.js:22381:3)
      at finishSyncRender (node_modules/react-dom/cjs/react-dom.development.js:21807:3)
      at performSyncWorkOnRoot (node_modules/react-dom/cjs/react-dom.development.js:21793:7)
      at scheduleUpdateOnFiber (node_modules/react-dom/cjs/react-dom.development.js:21188:7)
      at updateContainer (node_modules/react-dom/cjs/react-dom.development.js:24373:3)
      at legacyRenderSubtreeIntoContainer (node_modules/react-dom/cjs/react-dom.development.js:24774:5)
      at node_modules/react-dom/cjs/react-dom.development.js:24884:7
      at unbatchedUpdates (node_modules/react-dom/cjs/react-dom.development.js:21903:12)
      at Object.unmountComponentAtNode (node_modules/react-dom/cjs/react-dom.development.js:24883:5)
      at cleanupAtContainer (node_modules/@testing-library/react/dist/pure.js:145:21)
          at Set.forEach (<anonymous>)
      at cleanup (node_modules/@testing-library/react/dist/pure.js:136:21)
      at Object.<anonymous> (node_modules/@testing-library/react/dist/index.js:30:31)
      at TestScheduler.scheduleTests (node_modules/@jest/core/build/TestScheduler.js:333:13)
      at runJest (node_modules/@jest/core/build/runJest.js:404:19)
      at _run10000 (node_modules/@jest/core/build/cli/index.js:320:7)
      at runCLI (node_modules/@jest/core/build/cli/index.js:173:3)
```

Any ideas of what to poke at here would be helpful!

**Comment by lencioni** [comment]
I think I resolved this. In our Jest setup, we had a line that looks like this:

```ts
global.window = undefined;
```

I got past this error by changing it to this:

```ts
if (!global.window) {
  global.window = undefined;
}
```
