### ISSUE TITLE
ReferenceError: XMLHttpRequest is not defined

### ISSUE THREAD

**Issue by sschneider-ihre-pvs** [capricorn86/happy-dom#463]
I try to use happy-dom jest env in a quasar project and am facing this error when jest hits the line with 

```ts
import { installQuasarPlugin } from '@quasar/quasar-app-extension-testing-unit-jest';
```

stack trace
```
      at Object.<anonymous> (node_modules/quasar/dist/quasar.esm.prod.js:6:22776)
      at Object.<anonymous> (node_modules/@quasar/quasar-app-extension-testing-unit-jest/src/helpers/install-quasar-plugin.ts:4:1)
      at Object.<anonymous> (node_modules/@quasar/quasar-app-extension-testing-unit-jest/src/helpers/index.ts:1:1)
```

My guess, this is not used but has a reference in the dist file.

**Comment by capricorn86** [comment]
Thanks for reporting @sschneider-ihre-pvs! 🙂 

We have now added support for XMLHttpRequest.

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v7.8.0

**Comment by sschneider-ihre-pvs** [comment]
he hey, some xmas gifts come early :D
