### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by roggenbrot** [capricorn86/happy-dom#567]
I'm running into the following problem when trying to test a [prosemirror](https://prosemirror.net/) based react component

```
RangeError: Maximum call stack size exceeded

      at _classCallCheck (node_modules/prosemirror-state/dist/index.cjs:23:25)
      at new SelectionRange (node_modules/prosemirror-state/dist/index.cjs:199:3)
      at new Selection (node_modules/prosemirror-state/dist/index.cjs:45:30)
      at TextSelection._createSuperInternal (node_modules/prosemirror-state/dist/index.cjs:13:283)
      at new TextSelection (node_modules/prosemirror-state/dist/index.cjs:226:19)
      at Function.between (node_modules/prosemirror-state/dist/index.cjs:306:14)
      at selectionBetween (node_modules/prosemirror-view/dist/index.cjs:2584:40)
      at selectionFromDOM (node_modules/prosemirror-view/dist/index.cjs:2431:17)
      at readDOMChange (node_modules/prosemirror-view/dist/index.cjs:5025:18)
      at DOMObserver.handleDOMChange (node_modules/prosemirror-view/dist/index.cjs:5339:14)
      at DOMObserver.flush (node_modules/prosemirror-view/dist/index.cjs:4856:14)
      at MutationObserver.DOMObserver.observer [as callback] (node_modules/prosemirror-view/dist/index.cjs:4686:44)
      at HTMLElement.setAttributeNode (node_modules/happy-dom/src/nodes/element/Element.ts:838:15)
      at HTMLElement.setAttributeNode (node_modules/happy-dom/src/nodes/html-element/HTMLElement.ts:315:35)
      at HTMLElement.setAttributeNS (node_modules/happy-dom/src/nodes/element/Element.ts:541:8)
      at DOMTokenList.remove (node_modules/happy-dom/src/dom-token-list/DOMTokenList.ts:158:22)
      at selectionToDOM (node_modules/prosemirror-view/dist/index.cjs:2481:26)
      at DOMObserver.flush (node_modules/prosemirror-view/dist/index.cjs:4857:139)
      at MutationObserver.DOMObserver.observer [as callback] (node_modules/prosemirror-view/dist/index.cjs:4686:44)
      at HTMLElement.setAttributeNode (node_modules/happy-dom/src/nodes/element/Element.ts:838:15)
      at HTMLElement.setAttributeNode (node_modules/happy-dom/src/nodes/html-element/HTMLElement.ts:315:35)
      at HTMLElement.setAttributeNS (node_modules/happy-dom/src/nodes/element/Element.ts:541:8)
      at DOMTokenList.remove (node_modules/happy-dom/src/dom-token-list/DOMTokenList.ts:158:22)
      at selectionToDOM (node_modules/prosemirror-view/dist/index.cjs:2481:26)
      at DOMObserver.flush (node_modules/prosemirror-view/dist/index.cjs:4857:139)
      at MutationObserver.DOMObserver.observer [as callback] (node_modules/prosemirror-view/dist/index.cjs:4686:44)
      at HTMLElement.setAttributeNode (node_modules/happy-dom/src/nodes/element/Element.ts:838:15)
      at HTMLElement.setAttributeNode (node_modules/happy-dom/src/nodes/html-element/HTMLElement.ts:315:35)
      at HTMLElement.setAttributeNS (node_modules/happy-dom/src/nodes/element/Element.ts:541:8)
      at DOMTokenList.remove (node_modules/happy-dom/src/dom-token-list/DOMTokenList.ts:158:22)
      at selectionToDOM (node_modules/prosemirror-view/dist/index.cjs:2481:26)
      at DOMObserver.flush (node_modules/prosemirror-view/dist/index.cjs:4857:139)
      at MutationObserver.DOMObserver.observer [as callback] (node_modules/prosemirror-view/dist/index.cjs:4686:44)
      at HTMLElement.setAttributeNode (node_modules/happy-dom/src/nodes/element/Element.ts:838:15)
      at HTMLElement.setAttributeNode (node_modules/happy-dom/src/nodes/html-element/HTMLElement.ts:315:35)
      at HTMLElement.setAttributeNS (node_modules/happy-dom/src/nodes/element/Element.ts:541:8)
      at DOMTokenList.remove (node_modules/happy-dom/src/dom-token-list/DOMTokenList.ts:158:22)
      at selectionToDOM (node_modules/prosemirror-view/dist/index.cjs:2481:26)
      at DOMObserver.flush (node_modules/prosemirror-view/dist/index.cjs:4857:139)
      at MutationObserver.DOMObserver.observer [as callback] (node_modules/prosemirror-view/dist/index.cjs:4686:44)
      at HTMLElement.setAttributeNode (node_modules/happy-dom/src/nodes/element/Element.ts:838:15)
      at HTMLElement.setAttributeNode (node_modules/happy-dom/src/nodes/html-element/HTMLElement.ts:315:35)
      at HTMLElement.setAttributeNS (node_modules/happy-dom/src/nodes/element/Element.ts:541:8)
      at DOMTokenList.remove (node_modules/happy-dom/src/dom-token-list/DOMTokenList.ts:158:22)
      at selectionToDOM (node_modules/prosemirror-view/dist/index.cjs:2481:26)
      at DOMObserver.flush (node_modules/prosemirror-view/dist/index.cjs:4857:139)
      at MutationObserver.DOMObserver.observer [as callback] (node_modules/prosemirror-view/dist/index.cjs:4686:44)
      at HTMLElement.setAttributeNode (node_modules/happy-dom/src/nodes/element/Element.ts:838:15)
      at HTMLElement.setAttributeNode (node_modules/happy-dom/src/nodes/html-element/HTMLElement.ts:315:35)
      at HTMLElement.setAttributeNS (node_modules/happy-dom/src/nodes/element/Element.ts:541:8)
      at DOMTokenList.remove (node_modules/happy-dom/src/dom-token-list/DOMTokenList.ts:158:22)
      at selectionToDOM (node_modules/prosemirror-view/dist/index.cjs:2481:26)
      at DOMObserver.flush (node_modules/prosemirror-view/dist/index.cjs:4857:139)
      at MutationObserver.DOMObserver.observer [as callback] (node_modules/prosemirror-view/dist/index.cjs:4686:44)
      at HTMLElement.setAttributeNode (node_modules/happy-dom/src/nodes/element/Element.ts:838:15)
      at HTMLElement.setAttributeNode (node_modules/happy-dom/src/nodes/html-element/HTMLElement.ts:315:35)
      at HTMLElement.setAttributeNS (node_modules/happy-dom/src/nodes/element/Element.ts:541:8)
      at DOMTokenList.remove (node_modules/happy-dom/src/dom-token-list/DOMTokenList.ts:158:22)
      at selectionToDOM (node_modules/prosemirror-view/dist/index.cjs:2481:26)
      at DOMObserver.flush (node_modules/prosemirror-view/dist/index.cjs:4857:139)
      at MutationObserver.DOMObserver.observer [as callback] (node_modules/prosemirror-view/dist/index.cjs:4686:44)
      at HTMLElement.setAttributeNode (node_modules/happy-dom/src/nodes/element/Element.ts:838:15)
      at HTMLElement.setAttributeNode (node_modules/happy-dom/src/nodes/html-element/HTMLElement.ts:315:35)
      at HTMLElement.setAttributeNS (node_modules/happy-dom/src/nodes/element/Element.ts:541:8)
      at DOMTokenList.remove (node_modules/happy-dom/src/dom-token-list/DOMTokenList.ts:158:22)
      at selectionToDOM (node_modules/prosemirror-view/dist/index.cjs:2481:26)
      at DOMObserver.flush (node_modules/prosemirror-view/dist/index.cjs:4857:139)
      at MutationObserver.DOMObserver.observer [as callback] (node_modules/prosemirror-view/dist/index.cjs:4686:44)
      at HTMLElement.setAttributeNode (node_modules/happy-dom/src/nodes/element/Element.ts:838:15)
      at HTMLElement.setAttributeNode (node_modules/happy-dom/src/nodes/html-element/HTMLElement.ts:315:35)
      at HTMLElement.setAttributeNS (node_modules/happy-dom/src/nodes/element/Element.ts:541:8)
      at DOMTokenList.remove (node_modules/happy-dom/src/dom-token-list/DOMTokenList.ts:158:22)
      at selectionToDOM (node_modules/prosemirror-view/dist/index.cjs:2481:26)
      at DOMObserver.flush (node_modules/prosemirror-view/dist/index.cjs:4857:139)
      at MutationObserver.DOMObserver.observer [as callback] (node_modules/prosemirror-view/dist/index.cjs:4686:44)
      at HTMLElement.setAttributeNode (node_modules/happy-dom/src/nodes/element/Element.ts:838:15)
      at HTMLElement.setAttributeNode (node_modules/happy-dom/src/nodes/html-element/HTMLElement.ts:315:35)
      at HTMLElement.setAttributeNS (node_modules/happy-dom/src/nodes/element/Element.ts:541:8)
      at DOMTokenList.remove (node_modules/happy-dom/src/dom-token-list/DOMTokenList.ts:158:22)
      at selectionToDOM (node_modules/prosemirror-view/dist/index.cjs:2481:26)
      at DOMObserver.flush (node_modules/prosemirror-view/dist/index.cjs:4857:139)
      at MutationObserver.DOMObserver.observer [as callback] (node_modules/prosemirror-view/dist/index.cjs:4686:44)
      at HTMLElement.setAttributeNode (node_modules/happy-dom/src/nodes/element/Element.ts:838:15)
      at HTMLElement.setAttributeNode (node_modules/happy-dom/src/nodes/html-element/HTMLElement.ts:315:35)
      at HTMLElement.setAttributeNS (node_modules/happy-dom/src/nodes/element/Element.ts:541:8)
      at DOMTokenList.remove (node_modules/happy-dom/src/dom-token-list/DOMTokenList.ts:158:22)
      at selectionToDOM (node_modules/prosemirror-view/dist/index.cjs:2481:26)
      at DOMObserver.flush (node_modules/prosemirror-view/dist/index.cjs:4857:139)
      at MutationObserver.DOMObserver.observer [as callback] (node_modules/prosemirror-view/dist/index.cjs:4686:44)
      at HTMLElement.setAttributeNode (node_modules/happy-dom/src/nodes/element/Element.ts:838:15)
      at HTMLElement.setAttributeNode (node_modules/happy-dom/src/nodes/html-element/HTMLElement.ts:315:35)
      at HTMLElement.setAttributeNS (node_modules/happy-dom/src/nodes/element/Element.ts:541:8)
      at DOMTokenList.remove (node_modules/happy-dom/src/dom-token-list/DOMTokenList.ts:158:22)
      at selectionToDOM (node_modules/prosemirror-view/dist/index.cjs:2481:26)
      at DOMObserver.flush (node_modules/prosemirror-view/dist/index.cjs:4857:139)
      at MutationObserver.DOMObserver.observer [as callback] (node_modules/prosemirror-view/dist/index.cjs:4686:44)
      at HTMLElement.setAttributeNode (node_modules/happy-dom/src/nodes/element/Element.ts:838:15)
      at HTMLElement.setAttributeNode (node_modules/happy-dom/src/nodes/html-element/HTMLElement.ts:315:35)
      at HTMLElement.setAttributeNS (node_modules/happy-dom/src/nodes/element/Element.ts:541:8)
      at DOMTokenList.remove (node_modules/happy-dom/src/dom-token-list/DOMTokenList.ts:158:22)
```

Root cause seems to be an endless loop caused by prosemirror calling `setAttributeNode` in a observer with the same value.

Adding a check if the value of the attribute has really changed seems to resolve the issue, but don't know if this has any side effects

`Element.ts` 
```
// MutationObserver
if (this._observers.length > 0 && oldValue !== attribute.value) {
   ...
   ...
   ...
}
```

**Comment by marr** [comment]
I am also seeing this error using the _@vue/test-utils@1.3.0_ mount function.
