### ISSUE TITLE
jsdom -> happy-dom migration with vitest is not simple

### ISSUE THREAD

**Issue by VividLemon** [capricorn86/happy-dom#568]
Kind of a question for help, I'm trying to use happy-dom instead of jsdom using vitest, it should be as simple as changing the vitest environment setting. However, when I switch over, it comes with many issues. Such line as,
```js
    await $radios[0].trigger('click')
    expect(wrapper.vm.modelValue).toEqual('one')
```
Which worked fine before, doesn't seem to do anything. 

I also get weird fails saying `value.trim is not a function` on vue-test-utils...
```js
const wrapper = mount(FormSelectOptionGroup, {` 
```
Component mounting function. 

Also, on some other mounting functions, some will fill with `TypeError: Cannot set properties of undefined (setting 'hasOwnProperty')`, while others in the same file seemingly have no issues.

Any help would be appreciated. Here's the repo, if anyone wants to take a deeper look and help me figure out what I'm doing wrong. https://github.com/cdmoro/bootstrap-vue-3/tree/main/packages/bootstrap-vue-3

**Comment by EvHaus** [comment]
Running into a similar error with Jest too. Here's the full stacktrace:

```
   TypeError: value.trim is not a function

      at CSSStyleDeclarationPropertyManager.set (../../node_modules/happy-dom/src/css/declaration/utilities/CSSStyleDeclarationPropertyManager.ts:481:32)
      at CSSStyleDeclaration.setProperty (../../node_modules/happy-dom/src/css/declaration/AbstractCSSStyleDeclaration.ts:138:10)
      at CSSStyleDeclaration.set opacity [as opacity] (../../node_modules/happy-dom/src/css/declaration/CSSStyleDeclaration.ts:3557:8)
          at Function.assign (<anonymous>)
      at renderHTML (../../node_modules/framer-motion/dist/cjs/index.js:1016:12)
      at Object.render [as syncRender] (../../node_modules/framer-motion/dist/cjs/index.js:4321:9)
      at ../../node_modules/framer-motion/dist/cjs/index.js:85:40
      at commitHookEffectListMount (../../node_modules/react-dom/cjs/react-dom.development.js:23150:26)
      at commitLayoutEffectOnFiber (../../node_modules/react-dom/cjs/react-dom.development.js:23273:15)
      at commitLayoutMountEffects_complete (../../node_modules/react-dom/cjs/react-dom.development.js:24688:9)
      at commitLayoutEffects_begin (../../node_modules/react-dom/cjs/react-dom.development.js:24674:7)
      at commitLayoutEffects (../../node_modules/react-dom/cjs/react-dom.development.js:24612:3)
      at commitRootImpl (../../node_modules/react-dom/cjs/react-dom.development.js:26823:5)
      at commitRoot (../../node_modules/react-dom/cjs/react-dom.development.js:26682:5)
      at finishConcurrentRender (../../node_modules/react-dom/cjs/react-dom.development.js:25981:9)
      at performConcurrentWorkOnRoot (../../node_modules/react-dom/cjs/react-dom.development.js:25809:7)
      at workLoop (../../node_modules/scheduler/cjs/scheduler.development.js:266:34)
      at flushWork (../../node_modules/scheduler/cjs/scheduler.development.js:239:14)
      at performWorkUntilDeadline (../../node_modules/scheduler/cjs/scheduler.development.js:533:21)
      at Timeout._onTimeout (../../node_modules/happy-dom/src/window/Window.ts:549:4)
```

**Comment by VividLemon** [comment]
> Running into a similar error with Jest too. Here's the full stacktrace:

I've found jsdom and happy-dom conflict with each other on how they decide to resolve html attributes in the dom. In Vue, attr="true" equates to an "active" attribute, whereas attr="false" will resolve in an inactive one. It is related to how html is not a "programming" language, but markdown with no programming features. 

disabled="" in html goes to a correct disabled button, but disabled="false" is still a disabled button. only a non-existent disabled attribute is not disabled

This is where I found the major issue is. In Vue, disabled="false" will get resolved down correctly, and in jsdom, it correctly resolves this and makes Vue and jsdom work correctly with each other. In happy-dom, it will directly hand down disabled="false", which, will be equated to an active attribute. This screws everything up. In a new or small app this would be fine, and one could fix their Vue code (or other framework) to workaround it, and be more "html-like", but in my app, it is not feasible to convert. Which is a shame considering the 2k tests already written are getting quite slow 😞 Perhaps a Vitest solution could take control and resolve these prior to jsdom and happy-dom getting them, but it's doubtful.

**Comment by capricorn86** [comment]
Thanks for reporting @VividLemon! :slightly_smiling_face: 

The problem with `value.trim()` is probably related to a bug with the latest fixes for CSS. It has in that case been fixed in [v7.5.7](https://github.com/capricorn86/happy-dom/releases/tag/v7.5.7).

There is a bug for the other problem that was mentioned (#578).

**Comment by VividLemon** [comment]
> Thanks for reporting @VividLemon! 🙂
> 
> The problem with `value.trim()` is probably related to a bug with the latest fixes for CSS. It has in that case been fixed in [v7.5.7](https://github.com/capricorn86/happy-dom/releases/tag/v7.5.7).
> 
> There is a bug for the other problem that was mentioned (#578).

From what I noticed, the value.trim issue happens on class class HTMLOptionElementValueSanitizer. It's sanitizer functino will error out when value does not have a trim method. ie, objects. For example, 
```ts
 it('updating v-model (value) when selects correct option', async () => {
    const wrapper = mount(BFormSelect, {
      props: {
        options: ['one', 'two', {text: 'three', value: {three: 3}}],
        modelValue: 'one',
      },
    })

    const $options = wrapper.findAll('option')
    expect($options.length).toBe(3)
    expect($options[0].element.selected).toBe(true)

    // Select 2nd option
    await wrapper.setProps({modelValue: 'two'})
    expect($options[1].element.selected).toBe(true)

    // Select 3rd option
    await wrapper.setProps({modelValue: {three: 3}})
    expect($options[2].element.selected).toBe(true)
  })
```
Errors out when it hits the object one.

**Comment by VividLemon** [comment]
> There are two bugs for that as well (#571 and #618).
> 
> I will prioritize fixing those.

Thanks for that, I do think all of the errors do happen to stem from select and options.

**Comment by capricorn86** [comment]
I believe that the issues should be fixed now.

Big thanks to for @IGx89 for helping out with this! :slightly_smiling_face: 

Feel free to re-open otherwise.

You can read more about the releases here:
https://github.com/capricorn86/happy-dom/releases/tag/v7.5.12
https://github.com/capricorn86/happy-dom/releases/tag/v7.5.11

**Comment by chubetho** [comment]
Hi everyone, can somebody help me with this issue

`update:modelValue` emitted only empty string. This only happen with happy-dom. I've tried with js-dom and it works

here is reproduciton:
https://stackblitz.com/edit/vitest-dev-vitest-shz72q?file=vitest.config.ts

Thanks

**Comment by capricorn86** [comment]
@chubetho I think it is better if you open a new ticket for this issue. This message gets quite hidden as this ticket is closed.
