### ISSUE TITLE
RangeError: Invalid array length

### ISSUE THREAD

**Issue by lovetingyuan** [capricorn86/happy-dom#875]
**Describe the bug**
I use innerHTML to insert a piece of html, then error occurs.

**To Reproduce**

just use node to run code below:
```js
import { GlobalRegistrator } from '@happy-dom/global-registrator'
GlobalRegistrator.register()
document.write(`<html lang="zh-CN">
  <head>
    <meta charset="UTF-8" />
    <title></title>
  </head>
  <body>
    <div id="app">
    </div>
  </body>
</html>
`)
document.getElementById('app').innerHTML = `<a name="length"></a>`

```

**Expected behavior**
no error

**Screenshots**
```log

   this[name] = this._namedItems[name][0];
                           ^

RangeError: Invalid array length
    at HTMLCollection._appendNamedItem (/mnt/c/node_modules/.pnpm/happy-dom@9.9.2/node_modules/happy-dom/lib/nodes/element/HTMLCollection.js:43:28)
    at ElementUtility.appendChild (/mnt/node_modules/.pnpm/happy-dom@9.9.2/node_modules/happy-dom/lib/nodes/element/ElementUtility.js:43:43)
    at DocumentFragment.appendChild (/mnt/c/node_modules/.pnpm/happy-dom@9.9.2/node_modules/happy-dom/lib/nodes/document-fragment/DocumentFragment.js:146:41)
    at XMLParser.parse (/mnt/c/node_modules/.pnpm/happy-dom@9.9.2/node_modules/happy-dom/lib/xml-parser/XMLParser.js:91:41)
    at set innerHTML [as innerHTML] (/mnt/c/node_modules/.pnpm/happy-dom@9.9.2/node_modules/happy-dom/lib/nodes/element/Element.js:200:48)
    at render (file:///mnt/c/src/test.mjs:74:46)
```

**Device:**
 - windows 11
 - node 18.15.0

**Additional context**
I think the key point of the bug is the attribute `name="length"`, if I change the attribute name("name") or the value("length",) the bug disappears.

**Comment by capricorn86** [comment]
Thank you for reporting @lovetingyuan! :slightly_smiling_face: 

The issue has been fixed now.

This was a pretty serious bug. Hopefully it is not common to use names or id:s with the same name as methods and properties of the HTMLCollection class.

You can read more about the release here:
https://github.com/capricorn86/happy-dom/releases/tag/v9.10.5
